### ISSUE TITLE
Subscribe

### ISSUE THREAD

**Issue by quyetdc** [quyetdc/bookstore-2016#1]
- gather subscriber email and store to DB
(when user add email on subscribe section at near bottom)

- Send email to them to welcome to our system. Need html good format (we can google welcome email example) using sendgrid (or any tool you want)

**Comment by quyetdc** [comment]
Use local env or settings.yml (but ignore to add it to git)

**Comment by quyetdc** [comment]
set default from: colin@ebook-store.com

**Comment by thainqit** [comment]
![mail](https://cloud.githubusercontent.com/assets/8359014/13947983/20101c40-f050-11e5-8f72-f89c1f8ff0cd.png)
